version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "6532:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres